### ISSUE TITLE
Are "our" and "are" homophones?

### ISSUE THREAD

**Issue by talwrii** [TSMMark/homophone#59]
In my dialect they are (and it would appear that they are in many American dialects).

Wiktionary is my normal source for pronunciation information:

https://en.wiktionary.org/wiki/our
https://en.wiktionary.org/wiki/are

**Comment by TSMMark** [comment]
Thanks @talwrii. GitHub issues are not the place for it. In the footer of the website it says

> If you think we're missing any homophones, let us know by emailing me at al@homophone.com

**Comment by talwrii** [comment]
> GitHub issues are not the place for it

You of course mean you don't think github issues are the place for this :P.
Feel free to ignore the issue though.
